vm_count = (ENV['VM_COUNT'] || '1').to_i

print vm_count

Vagrant.configure("2") do |config|
  #  config.vm.box = "hashicorp/bionic64"
  #  config.vm.box_version = "1.0.282"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "docker" do |d|
    d.build_dir = "."
    d.has_ssh = true
  end

  config.ssh.username="root"
  config.ssh.password="root"

  (1..vm_count).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.network "forwarded_port", guest: 3389, host: 3389, auto_correct: true
      node.vm.network "forwarded_port", guest: 22, host: 2222, auto_correct: true
      node.vm.synced_folder "./userdata/node-#{i}/", "/home/lab", create:true
    end
  end
end
